# Mozilla User Preferences

/* Do not edit this file.
 *
 * If you make changes to this file while the application is running,
 * the changes will be overwritten when the application exits.
 *
 * To make a manual change to preferences, you can visit the URL about:config
 */

user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 1429398762);
user_pref("browser.cache.disk.capacity", 500);
user_pref("browser.cache.disk.smart_size.enabled", false);
user_pref("browser.cache.disk.smart_size.first_run", false);
user_pref("browser.cache.disk.smart_size.use_old_max", false);
user_pref("browser.cache.frecency_experiment", 1);
user_pref("browser.download.importedFromSqlite", true);
user_pref("browser.download.panel.firstSessionCompleted", true);
user_pref("browser.migration.version", 22);
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.places.smartBookmarksVersion", 7);
user_pref("browser.preferences.lastpanel", 0);
user_pref("browser.rights.3.shown", true);
user_pref("browser.safebrowsing.enabled", false);
user_pref("browser.safebrowsing.malware.enabled", false);
user_pref("browser.search.selectedEngine", "Google");
user_pref("browser.sessionstore.upgradeBackup.latestBuildID", "20150401080915");
user_pref("browser.slowStartup.averageTime", 1023);
user_pref("browser.slowStartup.samples", 4);
user_pref("browser.startup.homepage_override.buildID", "20140429194342");
user_pref("browser.startup.homepage_override.mstone", "24.5.0");
user_pref("datareporting.healthreport.nextDataSubmissionTime", "1429485161834");
user_pref("datareporting.policy.firstRunTime", "1429398761833");
user_pref("datareporting.sessions.current.activeTicks", 7);
user_pref("datareporting.sessions.current.clean", true);
user_pref("datareporting.sessions.current.firstPaint", 558);
user_pref("datareporting.sessions.current.main", 20);
user_pref("datareporting.sessions.current.sessionRestored", 595);
user_pref("datareporting.sessions.current.startTime", "1429400117637");
user_pref("datareporting.sessions.current.totalTime", 46);
user_pref("datareporting.sessions.currentIndex", 2);
user_pref("datareporting.sessions.previous.0", "{\"s\":1429398761459,\"a\":2,\"t\":8,\"c\":true,\"m\":40,\"fp\":1120,\"sr\":1169}");
user_pref("datareporting.sessions.previous.1", "{\"s\":1429399572965,\"a\":1,\"t\":7,\"c\":true,\"m\":11,\"fp\":675,\"sr\":723}");
user_pref("extensions.blocklist.pingCountVersion", -1);
user_pref("extensions.bootstrappedAddons", "{\"langpack-fr@iceweasel.mozilla.org\":{\"version\":\"24.5.0\",\"type\":\"locale\",\"descriptor\":\"/usr/lib/iceweasel/browser/extensions/langpack-fr@iceweasel.mozilla.org.xpi\"}}");
user_pref("extensions.databaseSchema", 16);
user_pref("extensions.disabledObsolete", true);
user_pref("extensions.enabledAddons", "%7B972ce4c6-7e08-4474-a285-3208198ce6fd%7D:31.6.0");
user_pref("extensions.installCache", "[{\"name\":\"app-global\",\"addons\":{\"langpack-fr@iceweasel.mozilla.org\":{\"descriptor\":\"/usr/lib/iceweasel/browser/extensions/langpack-fr@iceweasel.mozilla.org.xpi\",\"mtime\":1427870196000},\"{972ce4c6-7e08-4474-a285-3208198ce6fd}\":{\"descriptor\":\"/usr/lib/iceweasel/browser/extensions/{972ce4c6-7e08-4474-a285-3208198ce6fd}\",\"mtime\":1429400284000,\"rdfTime\":1427877418000}}}]");
user_pref("extensions.lastAppVersion", "31.6.0");
user_pref("extensions.lastPlatformVersion", "31.6.0");
user_pref("extensions.pendingOperations", false);
user_pref("gecko.buildID", "20150401080915");
user_pref("gecko.mstone", "31.6.0");
user_pref("intl.charsetmenu.browser.cache", "UTF-8");
user_pref("network.cookie.prefsMigrated", true);
user_pref("network.proxy.autoconfig_url", "http://pfp.etab.local/proxy.pac");
user_pref("network.proxy.type", 2);
user_pref("pdfjs.migrationVersion", 2);
user_pref("places.history.expiration.transient_current_max_pages", 13169);
user_pref("plugin.disable_full_page_plugin_for_types", "application/pdf");
user_pref("plugin.importedState", true);
user_pref("privacy.sanitize.migrateFx3Prefs", true);
user_pref("signon.rememberSignons", false);
user_pref("toolkit.startup.last_success", 1429400349);
user_pref("toolkit.telemetry.previousBuildID", "20150401080915");
user_pref("xpinstall.whitelist.add", "");
user_pref("xpinstall.whitelist.add.180", "");
user_pref("xpinstall.whitelist.add.36", "");
